### ISSUE TITLE
Get block ignores full transaction objects

### ISSUE THREAD

**Issue by plainerman** [vechain/web3-gear#11]
`eth_getBlockByHash `and `eth_getBlockByNumber` specify an additional parameter that allows to return the full transaction objects instead of only the hashes of the transactions. These parameters are already specified, but the actual request ignores this parameter and only returns the hashes.

**Comment by plainerman** [comment]
@uldaman could you take a look at it? I am not really familiar with the internal workings of thor.

**Comment by uldaman** [comment]
There is no way to directly meet this requirement in thor api. So here are two options:

1. The client traverses transactions after acquiring block.
2. Web3-gear takes over this requirement and traverses transactions before returning.

**Comment by plainerman** [comment]
For full support it would probably be better to implement it in web3-gear? What is your view on it?

**Comment by uldaman** [comment]
In our original scenario, only the lowest level of api was provided, and the business was resolved by the client itself. But if it is to make it compatible with Ethereum, it is reasonable for `web3-gear` to support this parameter. I will do this.

**Comment by uldaman** [comment]
I have done this on `feature-full-tx` branch, you can pull it down and test it, hope to receive your feedback..

87a31356a710450edb34025aadbb2d802a8d7b43

**Comment by plainerman** [comment]
Works great with web3j! Thank you very much.
