### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by i3bitcoin** [vechain/web3-gear#13]
Hi,

Is there any docs available for the api methods?
I'm searching the api with "create address" and "create transaction" methods on board.

**Comment by i3bitcoin** [comment]
Hello?

**Comment by uldaman** [comment]
Web3-Gear is just an Ethereum JSON-RPC adapter for users to use remix on Thor.

- eth_getCode
- eth_blockNumber
- eth_estimateGas
- eth_call
- eth_sendTransaction
- eth_getBalance
- eth_getTransactionByHash
- eth_getTransactionReceipt
- eth_getBlockByHash
- eth_getBlockByNumber
- get_block
- eth_newBlockFilter
- eth_uninstallFilter
- eth_getFilterChanges
- eth_getLogs
- debug_traceTransaction
- debug_storageRangeAt
