### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by maiocchim** [vechain/web3-gear#14]
running from command line on my windows 10 PC the command
**pip3 install web3-gear**

after a while I get this error:

_scrypt-1.2.1/libcperciva/crypto/crypto_aes.c(6): fatal error C1083: Is not possible to include: 'openssl/aes.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x86\\cl.exe' failed with exit status 2

    ----------------------------------------
Command "c:\users\maiocchim\appdata\local\programs\python\python37-32\python.exe -u -c "import setuptools, tokenize;__file__='[...]\AppData\\Local\\Temp\\pip-install-qhj6ti72\\scrypt\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record \AppData\Local\Temp\pip-record-gzv2l_hm\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in \AppData\Local\Temp\pip-install-qhj6ti72\scrypt\_

**Comment by uldaman** [comment]
Have you done these two steps?

1. Install Visual C++ Build Tools.
2. Install [scrypt-py](https://pypi.org/project/scrypt/#files) use the precompiled wheels.

**Comment by sangduongvan** [comment]
I got issue quite the same when I try to install it on Centos 7

"/usr/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-h49sy8rb/scrypt/setup.py';f=getattr(tokenize, 'open', open)(__file__)
;code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-tdj5xes_/install-record.txt --single-ver
sion-externally-managed --compile" failed with error code 1 in /tmp/pip-install-h49sy8rb/scrypt/

**Comment by uldaman** [comment]
@sangduongvan Try install [scrypt-py](https://pypi.org/project/scrypt/#files) use the precompiled wheels.

**Comment by uldaman** [comment]
I modified the readme c104446c2512535e00013f293c76a7c0265769ec, if still have  problem, please re-propose another issue.
