### ISSUE TITLE
Server-hosted web3-gear instance stops listening for commands

### ISSUE THREAD

**Issue by ShermanMeredith** [vechain/web3-gear#20]
Something triggers my web3-gear instance to stop listening for external commands.
The instance doesn't show any signs of having stopped listening, but does not react to JSON-RPC commands.

It can run smoothly for days at a time, and only stops working while I am making calls. I don't know what exactly triggers it to stop working.

The only solution has been to manually restart the web3-gear instance.

**Comment by uldaman** [comment]
What does the console show when gear stops working?

**Comment by ShermanMeredith** [comment]
- Server host was normal.
- Web3-gear process was running.
- Log showed no error.
However, the web3-gear server had no response to any external request

These are the last 10 lines from the log. Nothing out of the ordinary:
``received rpc request - eth_getBlockByNumber
received rpc request - eth_accounts
received rpc request - net_version
received rpc request - eth_accounts
received rpc request - net_version
received rpc request - eth_getBlockByNumber
received rpc request - eth_accounts
received rpc request - net_version
received rpc request - eth_accounts
received rpc request - net_version``

**Comment by ShermanMeredith** [comment]
This didn't just happen once; it keeps happening and I have to keep restarting web3-gear.

**Comment by uldaman** [comment]
So, are these logs before the gear stops working?

After the gear stops working, will the console not output the log when you make calls.?

**Comment by ShermanMeredith** [comment]
Correct

**Comment by uldaman** [comment]
When it happens next time, can you see if the gear port is being used?

```
lsof -i :8545
```

**Comment by ShermanMeredith** [comment]
Ok it happened again and this is what showed up when I did that command:
![1__ubuntu_ip-172-31-30-126_____ssh_](https://user-images.githubusercontent.com/10747672/58606192-5add7180-824f-11e9-9acf-7be9e1e67da7.png)

**Comment by uldaman** [comment]
Ok, this seems to be no problem.

When it happens next time, you try again with the following command (remember to replace it with your ip:port):

```
curl 'http://localhost:8545/' -H 'Content-Type: application/json' --data-binary '{"jsonrpc":"2.0","id":79,"method":"eth_getBlockByNumber","params":["latest",false]}'
```

:simple_smile: Web3-gear has always been alive on my computer, I can't reproduce this error. So I need your help to analyze.

**Comment by ShermanMeredith** [comment]
The command failed to create any response when the server stopped responding.
![image](https://user-images.githubusercontent.com/10747672/60053926-f49d1080-968d-11e9-83c0-42da11e2061f.png)

As soon as I restarted the Web3-gear instance I could send the command and got this:
![image](https://user-images.githubusercontent.com/10747672/60053864-d0d9ca80-968d-11e9-8f21-142a58623c37.png)

**Comment by uldaman** [comment]
At the moment, I can't judge what the problem is. I am trying to reproduce the bug. I will reply to you with the result. Thank you.

**Comment by uldaman** [comment]
I released a new version that uses a high-performance asynchronous architecture. You can update and try to use the new version to see if it solves your problem.

> However, the new version has not been tested on a large scale, please use it with caution in the production environment.
